### ISSUE TITLE
updating write only dictionaries

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/fastly-native-promises#181]
Some of the dictionaries are write only. Which makes this code a bit weird, as it'll always be updating dict items even if the entries don't exist because the response will be an object with 403 status. If the entry doesn't exist, updateDictItem will still create the entry. 

https://github.com/adobe/fastly-native-promises/blob/bdedcce07d70f6cc75b5058ee13991975ed6661a/src/index.js#L729-L754

**Expected behavior**
We should explicitly deal with write only dictionaries here to prevent confusion. 

**Version:**
6.2.0

**Comment by trieloff** [comment]
We can find out if the dictionary is write-only, but when it is write-only we can't find out if there is an entry. This is why always writing is the save choice.
