### ISSUE TITLE
Cannot read/update dictionary entries when key contains a slash

### ISSUE THREAD

**Issue by kptdobe** [adobe/fastly-native-promises#199]
**Description**
If dictionary key contains a slash, it is impossible to update. Read can be workaround by using `encodeURIComponent`

**To Reproduce**
```
await service.writeDictItem(undefined, 'dic', '/keywithapath', 'value');
const read = await service.readDictItem(undefined, 'dic', '/keywithapath');
```

This will fire a `FastlyError: Route not found`.

```
await service.writeDictItem(undefined, 'dic', '/keywithapath', 'value');
await service.writeDictItem(undefined, 'dic', '/keywithapath', 'newvalue');
```

This will fire an "already exist" exception (since read fails, it considers it as a new entry).

```
await service.writeDictItem(undefined, 'dic', '/keywithapath', 'value');
const read = await service.readDictItem(undefined, 'dic', encodeURIComponent('/keywithapath'));
```

works as a workaround for the read but update cannot be worked around.

**Expected behavior**
The slash should properly be handled.

**Comment by kptdobe** [comment]
This was revealed by https://github.com/adobe/helix-theblog-importer/issues/5

**Comment by trieloff** [comment]
Nice. And hard to discover with a fully-mocked test. If you care about a quick workaround, try using https://github.com/adobe/fastly-native-promises/blob/master/README.md#Fastly+bulkUpdateDictItems – this function does not encode the key in the URL, but puts it in the request body, which is probably safer.

**Comment by kptdobe** [comment]
Thanks, the workaround works nicely. Will use it for now.
