### ISSUE TITLE
Limit Concurrent API access

### ISSUE THREAD

**Issue by trieloff** [adobe/fastly-native-promises#241]
From Fastly:

> concurrent modifications to a service are not supported. This is a limitation that has been known for as long as the REST API has existed

We should limit concurrent POST/PUT requests accordingly.

**Comment by tripodsan** [comment]
are you sure you want to handle this here? I think the clients should be responsible...

**Comment by trieloff** [comment]
Yes, it's just another pitfall that the clients can avoid by using the library.
