### ISSUE TITLE
Allow reporting on rate limits/request numbers

### ISSUE THREAD

**Issue by trieloff** [adobe/fastly-native-promises#30]
See https://github.com/adobe/helix-cli/pull/515#pullrequestreview-201264719:
> It would be better to add those stats to https://github.com/adobe/fastly-native-promises, since https://github.com/adobe/helix-publish is using this.

**Comment by trieloff** [comment]
From @ejthurgo 
> Would be interesting to log the `x-timer` header. it would give us some clues into how long things are taking

**Comment by trieloff** [comment]
For timing, I'd need to find out what `S1553010731.965402,VS0,VE763` means.

**Comment by ejthurgo** [comment]
The first bit is the epoch start time. VS# is varnish start time (zero) and VE is varnish end time.
VE is basically how low we took to deliver.
https://docs.fastly.com/guides/performance-tuning/understanding-the-xtimer-header
