### ISSUE TITLE
CRUD for Synthetic Responses

### ISSUE THREAD

**Issue by trieloff** [adobe/fastly-native-promises#45]
To create redirects (see https://github.com/adobe/helix-cli/issues/587) we don't just need conditions (#34) and headers (#35) but also synthetic responses. 

API docs here: https://docs.fastly.com/api/config#response_object

**Comment by prashcr** [comment]
I'd like to work on this.

**Comment by prashcr** [comment]
Sorry, I'm unable to take this on at the moment. Please feel free to unassign.

**Comment by trieloff** [comment]
No worries, thanks for letting us know.
